# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
